version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${{ secrets.DB_HOST }}
      - DB_USER=${{ secrets.DB_USER }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - DB_NAME=${{ secrets.DB_NAME }}
      - PORT=${{ secrets.PORT }}
      - ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
    ports:
      - "3000:3000"
    environment:
      # Add any necessary frontend environment variables here

volumes:
  mysql-data:
