version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

volumes:
  mysql-data:
