version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: credentials
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app/data
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/app/build
    env_file:
      - ./frontend/.env
    networks:
      - my_network

volumes:
  backend-data:
  frontend-data:
  mysql-data:

networks:
  my_network:
    driver: bridge
