# Use the official Node.js image.
FROM node:14

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY src/package*.json ./

# Install production dependencies.
RUN npm install --production

# Copy local code to the container image.
COPY src .

# Copy the .env file if needed for build
COPY src/.env .env

# Build the app
RUN npm run build

# Serve the app
RUN npm install -g serve
CMD ["serve", "-s", "build"]
